<a href="https://colab.research.google.com/github/safwan207/E-Commerce-Performance-Profitability-Intelligence/blob/main/E-Commerce_Data_Cleaning_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd


df = pd.read_csv('ecommerce_sales_data.csv')
df.head()

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [6]:

print("--- Missing Values ---")
print(df.isnull().sum())
print("\n--- Column Types ---")
print(df.info())

--- Missing Values ---
Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
dtype: int64

--- Column Types ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   object
 1   Product Name  3500 non-null   object
 2   Category      3500 non-null   object
 3   Region        3500 non-null   object
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Profit        3500 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 191.5+ KB
None

In [7]:

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Month'] = df['Order Date'].dt.month_name()
print(df.dtypes)

Order Date      datetime64[ns]
Product Name            object
Category                object
Region                  object
Quantity                 int64
Sales                    int64
Profit                 float64
Month                   object
dtype: object

In [8]:
df['Profit_Margin_Pct'] = (df['Profit'] / df['Sales']) * 100
df.head()

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Month,Profit_Margin_Pct
0,2024-12-31,Printer,Office,North,4,3640,348.93,December,9.585989
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,November,8.899749
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,May,8.571697
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,March,25.810433
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,September,20.290766

In [9]:
df.to_csv('Ecommerce_Project_Cleaned.csv', index=False)